name: Deploy to S3

on:
  push:
    branches:
      - main # main 브랜치에 push될 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # 코드를 체크아웃

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22" # 사용하는 Node.js 버전

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: berakorean.com # S3 버킷 이름
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2 # S3 버킷 리전
          SOURCE_DIR: dist # 빌드된 폴더
