import schoolLogoImg from "./schoollogo.jpg";
import iconImg from "./icon.png";
import teacherProfileImg from "./teacher_profile.png";
import studentsImg from "./students.png";
import students2Img from "./students2.png";
import bannercomm1Img from "./bannercomm1.png";
import bannercomm2Img from "./bannercomm2.png";
import bannercomm3Img from "./bannercomm3.png";
import bannergame1Img from "./bannergame1.png";
import bannergame2Img from "./bannergame2.png";
import bannergame3Img from "./bannergame3.png";
import bannerinfo1Img from "./bannerinfo1.png";
import bannerteacher1Img from "./bannerteacher1.png";
import bannerteacher2Img from "./bannerteacher2.png";
import tutoring1Img from "./tutoring.png";
import berayoutubeImg from "./berayoutube.png";
import youtubeImg from "./youtubelogo.png";
import appleImg from "./applelogo.png";
import googleImg from "./g-logo.png";
import cafetalkImg from "./cafetalklogo.png";
import cafetalkpreviewImg from "./cafetalk.png";

export const schoolLogo = schoolLogoImg;
export const icon = iconImg;
export const teacherProfile = teacherProfileImg;
export const students = studentsImg;
export const students2 = students2Img;
export const bannercomm1 = bannercomm1Img;
export const bannercomm2 = bannercomm2Img;
export const bannercomm3 = bannercomm3Img;
export const bannergame1 = bannergame1Img;
export const bannergame2 = bannergame2Img;
export const bannergame3 = bannergame3Img;
export const bannerinfo1 = bannerinfo1Img;
export const bannerteacher1 = bannerteacher1Img;
export const bannerteacher2 = bannerteacher2Img;
export const tutoring1 = tutoring1Img;
export const berayoutube = berayoutubeImg;
export const youtube = youtubeImg;
export const apple = appleImg;
export const google = googleImg;
export const cafetalk = cafetalkImg;
export const cafetalkpreview = cafetalkpreviewImg;
